Added a CLI hook for existing API method for account balances
mrooney/mintapi pull request #624
Opened 2023-11-26 19:39 UTC by Ryanman

Hi folks. For anyone looking to leave mint, I think pulling balances out of accounts to get history is going to be key.

I am more of a .NET guy, so please forgive any errors and feel free to make any requests.

2023-11-27 00:01 UTC, burkematthew commented on mintapi/endpoints.py
@Ryanman can you explain why we need to manipulate the data? For the majority of the time we try to avoid doing such data manipulation and let this serve as a simple interface with Mint's endpoints. Couldn't your script do this sequence instead of relying on mintapi to do it?

2023-11-27 13:27 UTC, Ryanman commented on mintapi/endpoints.py
Out of these changes, there's really two parts:
* Enriching the response with Account Name/Type from the accounts endpoint. I can see how this violates the ethos, but both properties are included in the balances UI of Mint, and would be obviously useful if you're trying to join balances with something. Which a lot of people are going to need to do in the next month or so!
* The isZillow flag, which is included in the balance API response already but is just straight up wrong - false for every account type.

2023-12-01 20:23 UTC, Ryanman commented on mintapi/endpoints.py
@burkematthew just let me know if either this seems useful to merge in its entirety, without the additional helpful key columns, or if I should withdraw it!

2023-12-05 16:58 UTC, burkematthew requested changes
@Ryanman given that Mint is pending a shutdown, I'll approve this no problem.  That being said, there is a black error to correct.

2023-12-05 18:22 UTC, burkematthew approved these changes

2023-12-05 18:23 UTC, merged

2023-12-05 19:19 UTC, mrooney commented
Awesome, thanks! If this helps folks migrate, that's great!

2023-12-05 19:59 UTC, Ryanman commented
> Awesome, thanks! If this helps folks migrate, that's great!

Thank you guys so much for building this, I so wish I had found it earlier. It's taking a little of the sting out of the shutdown!